# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Emre\Desktop\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 333)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.home)
        self.instruction = QtWidgets.QWidget()
        self.instruction.setObjectName("instruction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.instruction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_no_instructions = QtWidgets.QLabel(self.instruction)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_no_instructions.setFont(font)
        self.label_no_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_no_instructions.setObjectName("label_no_instructions")
        self.gridLayout_2.addWidget(self.label_no_instructions, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.instruction)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        self.button_play.setObjectName("button_play")
        self.horizontalLayout.addWidget(self.button_play)
        self.button_instructions = QtWidgets.QPushButton(self.centralwidget)
        self.button_instructions.setObjectName("button_instructions")
        self.horizontalLayout.addWidget(self.button_instructions)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to the final boss of Ticket to Ride!"))
        self.label_2.setText(_translate("MainWindow", "Let\'s see what you got"))
        self.label_no_instructions.setText(_translate("MainWindow", "No instructions. Go play"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_instructions.setText(_translate("MainWindow", "Instructions"))
