from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_play = QtWidgets.QPushButton(self.home)
        self.button_play.setMinimumSize(QtCore.QSize(100, 50))
        self.button_play.setStyleSheet("font: 20px;")
        self.button_play.setObjectName("button_play")
        self.horizontalLayout.addWidget(self.button_play)
        self.button_instructions = QtWidgets.QPushButton(self.home)
        self.button_instructions.setMinimumSize(QtCore.QSize(100, 50))
        self.button_instructions.setStyleSheet("font: 20px;")
        self.button_instructions.setObjectName("button_instructions")
        self.horizontalLayout.addWidget(self.button_instructions)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_welcome = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.gridLayout.addWidget(self.label_welcome, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home)
        self.instruction = QtWidgets.QWidget()
        self.instruction.setObjectName("instruction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.instruction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_pressESC = QtWidgets.QLabel(self.instruction)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_pressESC.setFont(font)
        self.label_pressESC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pressESC.setObjectName("label_pressESC")
        self.gridLayout_2.addWidget(self.label_pressESC, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.button_play_instructions = QtWidgets.QPushButton(self.instruction)
        self.button_play_instructions.setMinimumSize(QtCore.QSize(300, 100))
        self.button_play_instructions.setStyleSheet("font: 45px;")
        self.button_play_instructions.setObjectName("button_play_instructions")
        self.horizontalLayout_3.addWidget(self.button_play_instructions)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.label_no_instructions = QtWidgets.QLabel(self.instruction)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_no_instructions.setFont(font)
        self.label_no_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_no_instructions.setObjectName("label_no_instructions")
        self.gridLayout_2.addWidget(self.label_no_instructions, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.instruction)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_instructions.setText(_translate("MainWindow", "Instructions"))
        self.label_2.setText(_translate("MainWindow", "Let\'s see what you got"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome to the final boss of Ticket to Ride!"))
        self.label_pressESC.setText(_translate("MainWindow", "You can try pressing \"ESC\""))
        self.button_play_instructions.setText(_translate("MainWindow", "Play"))
        self.label_no_instructions.setText(_translate("MainWindow", "No instructions. Go play"))